name: update-osp-nightly
run-name: Check for OSP nightly and create a PR
on: workflow_dispatch
  # schedule:
  #  - cron: '0 1 * * *'
jobs:
  update-osp-nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for new OSP nightly build
        run: |
          tag="v4.14-candidate"
          inspected=$(skopeo inspect docker://quay.io/openshift-pipeline/openshift-pipelines-pipelines-operator-bundle-container-index:$tag)
          created=$(echo "$inspected" | jq -r '.Created')
          echo "DEBUG: tag $tag created: $created"
          digest=$(echo "$inspected" | jq -r '.Digest')
          echo "digest: $digest"
          sed -i -E "s/sha256:[0-9a-f]{64}/sha256:${digest}/g" catalog-source.yaml
      - name: Create Pull Request
        run: gh pr create --title "Automated changes by GitHub action" --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
